name: CI/CD Pipeline

# This workflow will run when there's a push to the main branch
on:
  push:
    branches:
      - main

jobs:
  # Job to build and push Docker image
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (credentials stored as secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t yourusername/devops-todo-app .

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push yourusername/devops-todo-app

  # Job to deploy the app using Docker Compose
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push  # This job runs only after build_and_push
    steps:
      # Step 1: Checkout the code (again, if needed)
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: SSH into your server and deploy using Docker Compose
      - name: Deploy app on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}  # Your server IP
          username: ${{ secrets.SERVER_USER }}  # SSH username
          key: ${{ secrets.SERVER_SSH_KEY }}  # SSH private key stored in GitHub secrets
          script: |
            cd /path/to/your/app
            docker-compose pull  # Pull the latest image from Docker Hub
            docker-compose up -d  # Start the container in detached mode
