name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs targeting the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repo so the workflow can access it

    # Step to log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker password

    # Step to build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-todo-app .

    # Step to push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/devops-todo-app

    # Step to deploy the app on a server using docker-compose
    - name: Deploy app using Docker Compose
      uses: appleboy/ssh-action@v0.1.6  # SSH into the server
      with:
        host: ${{ secrets.SERVER_HOST }}  # Server IP or hostname
        username: ${{ secrets.SERVER_USER }}  # Server SSH username
        key: ${{ secrets.SERVER_SSH_KEY }}  # SSH private key
        script: |
          cd /path/to/your/project  # Navigate to your app's directory
          docker pull ${{ secrets.DOCKER_USERNAME }}/devops-todo-app  # Pull the latest image
          docker-compose up -d  # Start the container using docker-compose
